//! Test-only oracle: validates outgoing request bodies against GitHub's
//! published OpenAPI request-body schemas (vendored under
//! `tests/fixtures/openapi/`, regenerated by the `regen_openapi_fixtures`
//! binary). The mock `TestServer` used by the executor tests otherwise accepts
//! any body, which let two GitHub-rejected (422) payloads gain passing tests;
//! this module is the schema check that catches that whole class of bug.
//!
//! The vendored fixtures already fold in the small set of "local tightenings"
//! (constraints GitHub enforces at runtime but omits from its schema), so this
//! loader just compiles the fixtures as-is.

use std::sync::LazyLock;

use jsonschema::Validator;
use serde_json::Value;

/// A GitHub endpoint whose request body we validate. One per body-bearing
/// `send_*` call site in [`crate::github::client`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Endpoint {
    CreateRuleset,
    UpdateRuleset,
    UpdateRepository,
    CreateGitRef,
    UpdateFileContents,
    CreatePullRequest,
    SetForkPrApproval,
}

impl Endpoint {
    pub(crate) const ALL: [Endpoint; 7] = [
        Endpoint::CreateRuleset,
        Endpoint::UpdateRuleset,
        Endpoint::UpdateRepository,
        Endpoint::CreateGitRef,
        Endpoint::UpdateFileContents,
        Endpoint::CreatePullRequest,
        Endpoint::SetForkPrApproval,
    ];
}

/// `(endpoint, method, templated path)`. A `{placeholder}` segment matches one
/// concrete segment, except a trailing `{path}` which matches the remainder
/// (GitHub's contents path can contain slashes).
const ROUTES: &[(Endpoint, &str, &str)] = &[
    (
        Endpoint::CreateRuleset,
        "POST",
        "/repos/{owner}/{repo}/rulesets",
    ),
    (
        Endpoint::UpdateRuleset,
        "PUT",
        "/repos/{owner}/{repo}/rulesets/{ruleset_id}",
    ),
    (Endpoint::UpdateRepository, "PATCH", "/repos/{owner}/{repo}"),
    (
        Endpoint::CreateGitRef,
        "POST",
        "/repos/{owner}/{repo}/git/refs",
    ),
    (
        Endpoint::UpdateFileContents,
        "PUT",
        "/repos/{owner}/{repo}/contents/{path}",
    ),
    (
        Endpoint::CreatePullRequest,
        "POST",
        "/repos/{owner}/{repo}/pulls",
    ),
    (
        Endpoint::SetForkPrApproval,
        "PUT",
        "/repos/{owner}/{repo}/actions/permissions/fork-pr-contributor-approval",
    ),
];

fn compile(source: &str, name: &str) -> Validator {
    let schema: Value = serde_json::from_str(source)
        .unwrap_or_else(|error| panic!("openapi fixture {name} is not valid JSON: {error}"));
    jsonschema::draft7::new(&schema).unwrap_or_else(|error| {
        panic!("openapi fixture {name} is not a valid JSON Schema: {error}")
    })
}

macro_rules! fixture_validator {
    ($ident:ident, $file:literal) => {
        static $ident: LazyLock<Validator> = LazyLock::new(|| {
            compile(
                include_str!(concat!(
                    env!("CARGO_MANIFEST_DIR"),
                    "/tests/fixtures/openapi/",
                    $file
                )),
                $file,
            )
        });
    };
}

fixture_validator!(CREATE_RULESET, "create-ruleset.request.json");
fixture_validator!(UPDATE_RULESET, "update-ruleset.request.json");
fixture_validator!(UPDATE_REPOSITORY, "update-repository.request.json");
fixture_validator!(CREATE_GIT_REF, "create-git-ref.request.json");
fixture_validator!(UPDATE_FILE_CONTENTS, "update-file-contents.request.json");
fixture_validator!(CREATE_PULL_REQUEST, "create-pull-request.request.json");
fixture_validator!(SET_FORK_PR_APPROVAL, "set-fork-pr-approval.request.json");

pub(crate) fn validator(endpoint: Endpoint) -> &'static Validator {
    match endpoint {
        Endpoint::CreateRuleset => &CREATE_RULESET,
        Endpoint::UpdateRuleset => &UPDATE_RULESET,
        Endpoint::UpdateRepository => &UPDATE_REPOSITORY,
        Endpoint::CreateGitRef => &CREATE_GIT_REF,
        Endpoint::UpdateFileContents => &UPDATE_FILE_CONTENTS,
        Endpoint::CreatePullRequest => &CREATE_PULL_REQUEST,
        Endpoint::SetForkPrApproval => &SET_FORK_PR_APPROVAL,
    }
}

fn segment_matches(template: &str, concrete: &str) -> bool {
    (template.starts_with('{') && template.ends_with('}')) || template == concrete
}

fn path_matches(template: &str, concrete: &str) -> bool {
    let template: Vec<&str> = template.trim_matches('/').split('/').collect();
    let concrete: Vec<&str> = concrete.trim_matches('/').split('/').collect();

    if let Some((last, head)) = template.split_last()
        && *last == "{path}"
    {
        return concrete.len() >= template.len()
            && head
                .iter()
                .zip(&concrete)
                .all(|(t, c)| segment_matches(t, c));
    }

    template.len() == concrete.len()
        && template
            .iter()
            .zip(&concrete)
            .all(|(t, c)| segment_matches(t, c))
}

/// Resolves a concrete `(method, path)` to the endpoint whose schema governs its
/// body, or `None` if it is not one of the body-bearing write endpoints (GETs,
/// DELETEs, and anything else are left unvalidated).
pub(crate) fn resolve(method: &str, path: &str) -> Option<Endpoint> {
    let path = path.split('?').next().unwrap_or(path);
    ROUTES
        .iter()
        .find(|(_, m, template)| method.eq_ignore_ascii_case(m) && path_matches(template, path))
        .map(|(endpoint, _, _)| *endpoint)
}

/// Checks a request body against the schema for its endpoint. `Ok(())` when the
/// endpoint is not one we validate or the body conforms; `Err` with a
/// human-readable report (endpoint, path, and every schema violation) otherwise.
pub(crate) fn check_request_body(method: &str, path: &str, body: &str) -> Result<(), String> {
    let Some(endpoint) = resolve(method, path) else {
        return Ok(());
    };
    let value: Value = serde_json::from_str(body)
        .map_err(|error| format!("{endpoint:?} body is not valid JSON: {error}\nbody: {body}"))?;
    let validator = validator(endpoint);
    if validator.is_valid(&value) {
        return Ok(());
    }
    let violations: Vec<String> = validator
        .iter_errors(&value)
        .map(|error| format!("  at {}: {error}", error.instance_path()))
        .collect();
    Err(format!(
        "{endpoint:?} request body ({method} {path}) does not conform to GitHub's published schema:\n{}\nbody: {body}",
        violations.join("\n")
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn valid(method: &str, path: &str, body: Value) {
        assert_eq!(
            check_request_body(method, path, &body.to_string()),
            Ok(()),
            "expected body to conform"
        );
    }

    fn invalid(method: &str, path: &str, body: Value) {
        assert!(
            check_request_body(method, path, &body.to_string()).is_err(),
            "expected body to be rejected: {body}"
        );
    }

    #[test]
    fn every_fixture_compiles_as_a_json_schema() {
        for endpoint in Endpoint::ALL {
            // Forces the LazyLock, which panics with context on a bad fixture.
            let _ = validator(endpoint);
        }
    }

    #[test]
    fn router_maps_write_endpoints() {
        assert_eq!(
            resolve("POST", "/repos/o/r/rulesets"),
            Some(Endpoint::CreateRuleset)
        );
        assert_eq!(
            resolve("PUT", "/repos/o/r/rulesets/99"),
            Some(Endpoint::UpdateRuleset)
        );
        assert_eq!(
            resolve("PATCH", "/repos/o/r"),
            Some(Endpoint::UpdateRepository)
        );
        assert_eq!(
            resolve("POST", "/repos/o/r/git/refs"),
            Some(Endpoint::CreateGitRef)
        );
        assert_eq!(
            resolve("PUT", "/repos/o/r/contents/.github/workflows/ci.yml"),
            Some(Endpoint::UpdateFileContents),
            "the {{path}} placeholder must span multiple segments"
        );
        assert_eq!(
            resolve("POST", "/repos/o/r/pulls"),
            Some(Endpoint::CreatePullRequest)
        );
        assert_eq!(
            resolve(
                "PUT",
                "/repos/o/r/actions/permissions/fork-pr-contributor-approval"
            ),
            Some(Endpoint::SetForkPrApproval)
        );
        assert_eq!(
            resolve("POST", "/repos/o/r/rulesets?foo=bar"),
            Some(Endpoint::CreateRuleset)
        );
    }

    #[test]
    fn router_ignores_non_write_requests() {
        assert_eq!(resolve("GET", "/repos/o/r/rulesets/99"), None);
        assert_eq!(resolve("GET", "/repos/o/r"), None);
        assert_eq!(
            resolve("DELETE", "/repos/o/r/branches/main/protection"),
            None
        );
    }

    // The two historical 422 bugs, proven catchable at the schema level.

    #[test]
    fn ref_name_condition_requires_include_and_exclude() {
        // Bug #1 (commit 94d775f): the published schema marks these optional, so
        // this only passes because of the local tightening baked into the fixture.
        invalid(
            "PUT",
            "/repos/o/r/rulesets/99",
            json!({"name": "x", "enforcement": "active",
                   "conditions": {"ref_name": {"include": []}}}),
        );
        valid(
            "PUT",
            "/repos/o/r/rulesets/99",
            json!({"name": "x", "enforcement": "active",
                   "conditions": {"ref_name": {"include": [], "exclude": []}}}),
        );
    }

    #[test]
    fn pull_request_rule_requires_review_parameters() {
        // Bug #2 (commit 2e8d8e8): the published schema itself requires these.
        let pr_rule = |params: Value| {
            json!({"name": "x", "enforcement": "active",
                   "rules": [{"type": "pull_request", "parameters": params}]})
        };
        invalid(
            "POST",
            "/repos/o/r/rulesets",
            pr_rule(json!({"required_approving_review_count": 0})),
        );
        valid(
            "POST",
            "/repos/o/r/rulesets",
            pr_rule(json!({
                "required_approving_review_count": 0,
                "dismiss_stale_reviews_on_push": false,
                "require_code_owner_review": false,
                "require_last_push_approval": false,
                "required_review_thread_resolution": false
            })),
        );
    }

    #[test]
    fn simple_endpoints_accept_well_formed_bodies() {
        valid(
            "POST",
            "/repos/o/r/git/refs",
            json!({"ref": "refs/heads/x", "sha": "deadbeef"}),
        );
        valid(
            "PUT",
            "/repos/o/r/contents/.envrc",
            json!({"message": "m", "content": "dXNlIGZsYWtlCg==", "branch": "main"}),
        );
        valid(
            "POST",
            "/repos/o/r/pulls",
            json!({"title": "t", "head": "h", "base": "b", "body": "x"}),
        );
        valid("PATCH", "/repos/o/r", json!({"allow_squash_merge": true}));
        valid(
            "PUT",
            "/repos/o/r/actions/permissions/fork-pr-contributor-approval",
            json!({"approval_policy": "all_external_contributors"}),
        );
    }

    #[test]
    fn enum_and_required_violations_are_rejected() {
        invalid(
            "PUT",
            "/repos/o/r/actions/permissions/fork-pr-contributor-approval",
            json!({"approval_policy": "not_a_real_policy"}),
        );
        invalid(
            "POST",
            "/repos/o/r/git/refs",
            json!({"ref": "refs/heads/x"}),
        );
    }
}

/// Layer A: for every request type the executor can serialize, assert that
/// serde's output conforms to GitHub's published schema — for *all* values the
/// type can hold, a superset of what the planner actually emits. Where Layer B
/// (the `TestServer` check) validates the concrete payloads a given test drives,
/// this validates the type itself, catching a schema mismatch even when no
/// executor test exercises the offending path. "Leverage compute at the API
/// boundary."
#[cfg(test)]
mod request_body_conformance {
    use proptest::prelude::*;

    use super::{Endpoint, validator};
    use crate::github::types::{
        BypassActor, BypassActorType, BypassMode, CreateGitReference, CreatePullRequest,
        ForkPrApprovalPermission, ForkPrApprovalPolicy, MergeMethod, PullRequestParameters,
        RefNameCondition, RepositoryUpdate, RequiredStatusCheck, RequiredStatusChecksParameters,
        RulesetConditions, RulesetEnforcement, RulesetRule, RulesetRuleType, RulesetTarget,
        UpdateRepositoryFile, UpdateRulesetRequest,
    };

    /// Serializes `value` and asserts it conforms to `endpoint`'s schema, with a
    /// report of every violation (and the offending JSON) on failure.
    fn assert_conforms(endpoint: Endpoint, value: &impl serde::Serialize) {
        let json = serde_json::to_value(value).expect("request type serializes to JSON");
        let validator = validator(endpoint);
        if validator.is_valid(&json) {
            return;
        }
        let violations: Vec<String> = validator
            .iter_errors(&json)
            .map(|error| format!("  at {}: {error}", error.instance_path()))
            .collect();
        panic!(
            "{endpoint:?} serialization does not conform to GitHub's published schema:\n{}\nvalue: {json}",
            violations.join("\n")
        );
    }

    fn ruleset_target() -> impl Strategy<Value = RulesetTarget> {
        prop_oneof![
            Just(RulesetTarget::Branch),
            Just(RulesetTarget::Tag),
            Just(RulesetTarget::Push),
        ]
    }

    fn ruleset_enforcement() -> impl Strategy<Value = RulesetEnforcement> {
        prop_oneof![
            Just(RulesetEnforcement::Active),
            Just(RulesetEnforcement::Evaluate),
            Just(RulesetEnforcement::Disabled),
        ]
    }

    fn merge_method() -> impl Strategy<Value = MergeMethod> {
        prop_oneof![
            Just(MergeMethod::Merge),
            Just(MergeMethod::Squash),
            Just(MergeMethod::Rebase),
        ]
    }

    fn required_status_check() -> impl Strategy<Value = RequiredStatusCheck> {
        (any::<String>(), proptest::option::of(any::<u64>())).prop_map(
            |(context, integration_id)| RequiredStatusCheck {
                context,
                integration_id,
            },
        )
    }

    fn pull_request_parameters() -> impl Strategy<Value = PullRequestParameters> {
        (
            any::<bool>(),
            any::<bool>(),
            any::<bool>(),
            // The schema bounds this to [0, 10]; exercise the full range.
            0u32..=10,
            any::<bool>(),
            proptest::collection::vec(merge_method(), 0..4),
        )
            .prop_map(
                |(
                    dismiss_stale_reviews_on_push,
                    require_code_owner_review,
                    require_last_push_approval,
                    required_approving_review_count,
                    required_review_thread_resolution,
                    allowed_merge_methods,
                )| PullRequestParameters {
                    dismiss_stale_reviews_on_push,
                    require_code_owner_review,
                    require_last_push_approval,
                    required_approving_review_count,
                    required_review_thread_resolution,
                    allowed_merge_methods,
                    // Left empty: `extra` carries fields GitHub sent that we don't
                    // model, which are schema-valid by construction; generating
                    // arbitrary keys here would risk false schema violations.
                    extra: serde_json::Map::new(),
                },
            )
    }

    fn required_status_checks_parameters() -> impl Strategy<Value = RequiredStatusChecksParameters>
    {
        (
            proptest::collection::vec(required_status_check(), 0..3),
            any::<bool>(),
            proptest::option::of(any::<bool>()),
        )
            .prop_map(
                |(
                    required_status_checks,
                    strict_required_status_checks_policy,
                    do_not_enforce_on_create,
                )| RequiredStatusChecksParameters {
                    required_status_checks,
                    strict_required_status_checks_policy,
                    do_not_enforce_on_create,
                    extra: serde_json::Map::new(),
                },
            )
    }

    /// The rule kinds the planner can construct. Unknown-kind `Other` rules with
    /// arbitrary parameters are deliberately omitted: the planner never builds
    /// one, and round-tripped `Other` rules are schema-valid by construction
    /// (GitHub sent them) — the facts roundtrip proptest covers their
    /// serialization. The parameterless kinds it does emit are exercised as
    /// bare `Other { parameters: None }` (a `{"type": …}` the schema accepts).
    fn ruleset_rule() -> impl Strategy<Value = RulesetRule> {
        prop_oneof![
            pull_request_parameters().prop_map(RulesetRule::PullRequest),
            required_status_checks_parameters().prop_map(RulesetRule::RequiredStatusChecks),
            prop_oneof![
                Just(RulesetRuleType::Creation),
                Just(RulesetRuleType::Update),
                Just(RulesetRuleType::Deletion),
                Just(RulesetRuleType::RequiredLinearHistory),
                Just(RulesetRuleType::RequiredSignatures),
                Just(RulesetRuleType::NonFastForward),
            ]
            .prop_map(RulesetRule::parameterless),
        ]
    }

    fn bypass_actor_type() -> impl Strategy<Value = BypassActorType> {
        // Every variant we model is in the schema's actor_type enum.
        prop_oneof![
            Just(BypassActorType::OrganizationAdmin),
            Just(BypassActorType::RepositoryRole),
            Just(BypassActorType::Team),
            Just(BypassActorType::Integration),
            Just(BypassActorType::DeployKey),
        ]
    }

    fn bypass_mode() -> impl Strategy<Value = BypassMode> {
        prop_oneof![Just(BypassMode::Always), Just(BypassMode::PullRequest)]
    }

    fn bypass_actor() -> impl Strategy<Value = BypassActor> {
        (
            proptest::option::of(any::<u64>()),
            bypass_actor_type(),
            bypass_mode(),
        )
            .prop_map(|(actor_id, actor_type, bypass_mode)| BypassActor {
                actor_id,
                actor_type,
                bypass_mode,
            })
    }

    fn ref_name_condition() -> impl Strategy<Value = RefNameCondition> {
        (
            proptest::collection::vec(any::<String>(), 0..3),
            proptest::collection::vec(any::<String>(), 0..3),
        )
            .prop_map(|(include, exclude)| RefNameCondition { include, exclude })
    }

    fn ruleset_conditions() -> impl Strategy<Value = RulesetConditions> {
        proptest::option::of(ref_name_condition())
            .prop_map(|ref_name| RulesetConditions { ref_name })
    }

    fn update_ruleset_request() -> impl Strategy<Value = UpdateRulesetRequest> {
        (
            any::<String>(),
            ruleset_target(),
            ruleset_enforcement(),
            proptest::option::of(ruleset_conditions()),
            proptest::collection::vec(bypass_actor(), 0..3),
            proptest::collection::vec(ruleset_rule(), 0..5),
        )
            .prop_map(
                |(name, target, enforcement, conditions, bypass_actors, rules)| {
                    UpdateRulesetRequest {
                        name,
                        target,
                        enforcement,
                        conditions,
                        bypass_actors,
                        rules,
                    }
                },
            )
    }

    fn repository_update() -> impl Strategy<Value = RepositoryUpdate> {
        proptest::collection::vec(proptest::option::of(any::<bool>()), 9..=9).prop_map(|flags| {
            RepositoryUpdate {
                private: flags[0],
                archived: flags[1],
                disabled: flags[2],
                allow_auto_merge: flags[3],
                delete_branch_on_merge: flags[4],
                allow_update_branch: flags[5],
                allow_squash_merge: flags[6],
                allow_merge_commit: flags[7],
                allow_rebase_merge: flags[8],
            }
        })
    }

    fn create_git_reference() -> impl Strategy<Value = CreateGitReference> {
        (any::<String>(), any::<String>())
            .prop_map(|(reference, sha)| CreateGitReference { reference, sha })
    }

    fn update_repository_file() -> impl Strategy<Value = UpdateRepositoryFile> {
        (
            any::<String>(),
            any::<String>(),
            proptest::option::of(any::<String>()),
            any::<String>(),
        )
            .prop_map(|(message, content, sha, branch)| UpdateRepositoryFile {
                message,
                content,
                sha,
                branch,
            })
    }

    fn create_pull_request() -> impl Strategy<Value = CreatePullRequest> {
        (
            any::<String>(),
            any::<String>(),
            any::<String>(),
            any::<String>(),
        )
            .prop_map(|(title, head, base, body)| CreatePullRequest {
                title,
                head,
                base,
                body,
            })
    }

    fn fork_pr_approval_permission() -> impl Strategy<Value = ForkPrApprovalPermission> {
        prop_oneof![
            Just(ForkPrApprovalPolicy::AllExternalContributors),
            Just(ForkPrApprovalPolicy::FirstTimeContributorsNewToGithub),
            Just(ForkPrApprovalPolicy::FirstTimeContributors),
        ]
        .prop_map(|approval_policy| ForkPrApprovalPermission { approval_policy })
    }

    proptest! {
        #[test]
        fn update_ruleset_request_conforms(request in update_ruleset_request()) {
            // The same body type is sent to both the create (POST) and update
            // (PUT) endpoints, so it must satisfy both schemas.
            assert_conforms(Endpoint::CreateRuleset, &request);
            assert_conforms(Endpoint::UpdateRuleset, &request);
        }

        #[test]
        fn repository_update_conforms(request in repository_update()) {
            assert_conforms(Endpoint::UpdateRepository, &request);
        }

        #[test]
        fn create_git_reference_conforms(request in create_git_reference()) {
            assert_conforms(Endpoint::CreateGitRef, &request);
        }

        #[test]
        fn update_repository_file_conforms(request in update_repository_file()) {
            assert_conforms(Endpoint::UpdateFileContents, &request);
        }

        #[test]
        fn create_pull_request_conforms(request in create_pull_request()) {
            assert_conforms(Endpoint::CreatePullRequest, &request);
        }

        #[test]
        fn fork_pr_approval_permission_conforms(request in fork_pr_approval_permission()) {
            assert_conforms(Endpoint::SetForkPrApproval, &request);
        }
    }
}
